[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=42", # At least v42 of setuptools required.
  "versioningit",
]

[project]
name = "lorrystream"
description = """\
  A lightweight and polyglot stream-processing library, to be used as a data backplane-, message relay-, or \
  pipeline-subsystem.\
  """
readme = "README.md"
keywords = [
  "amqp",
  "data",
  "export",
  "import",
  "kinesis",
  "mqtt",
  "pandas",
  "rdbms",
  "sql",
  "stream",
]
license = "MIT"
authors = [
  { name = "Andreas Motl", email = "andreas.motl@panodata.org" },
]
requires-python = ">=3.9"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Customer Service",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Manufacturing",
  "Intended Audience :: Science/Research",
  "Intended Audience :: System Administrators",
  "Intended Audience :: Telecommunications Industry",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Unix",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Adaptive Technologies",
  "Topic :: Communications",
  "Topic :: Database",
  "Topic :: Documentation",
  "Topic :: Education",
  "Topic :: Internet",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Office/Business",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development :: Embedded Systems",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Object Brokering",
  "Topic :: Software Development :: Pre-processors",
  "Topic :: Software Development :: Quality Assurance",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development :: Version Control",
  "Topic :: System :: Archiving",
  "Topic :: System :: Benchmark",
  "Topic :: System :: Clustering",
  "Topic :: System :: Distributed Computing",
  "Topic :: System :: Hardware",
  "Topic :: System :: Logging",
  "Topic :: System :: Monitoring",
  "Topic :: System :: Networking",
  "Topic :: System :: Systems Administration",
  "Topic :: Text Processing",
  "Topic :: Utilities",
]
dynamic = [
  "version",
]
dependencies = [
  "boltons",
  "click<9",
  "colorama<1",
  "colorlog",
  "commons-codec>=0.0.24",
  "dask",
  "funcy",
  "influxdb",
  "influxdb-client[ciso]",
  "orjson",
  "paho-mqtt",
  "pandas<2.4",
  "pika<1.5",
  "simplejson<5",
  "sqlalchemy-cratedb>=0.38.0",
  "streamz",
  "tomli",
  "toolz",
]
optional-dependencies.all = [
  "lorrystream[carabas]",
]
optional-dependencies.carabas = [
  "async-kinesis<3",
  "aws-lambda-layer<0.6",
  "cottonformation<1.2",
  "localstack<2026.8",
]
optional-dependencies.develop = [
  "black<27",
  "mypy<2.4",
  "pika-stubs<0.2",
  "poethepoet<1",
  "pyproject-fmt<3",
  "ruff<0.16",
  "validate-pyproject<1",
]
optional-dependencies.docs = [
  "furo>=2024",
  "myst-parser[linkify]>=0.18,<5",
  "sphinx<8",
  "sphinx-autobuild>=2024",
  "sphinx-copybutton",
  "sphinx-design-elements<1",
  "sphinxcontrib-mermaid<3",
  "sphinxext-opengraph<1",
]
optional-dependencies.ingestr = [
  "async-kinesis<3",
]
optional-dependencies.release = [
  "build<2",
  "twine<7",
]
optional-dependencies.test = [
  "cratedb-toolkit[testing]>=0.0.20",
  "localstack-utils<1.1",
  "pytest<10",
  "pytest-asyncio<2",
  "pytest-cov<8",
  "pytest-mock<4",
  "pytest-mqtt>=0.4.2,<0.8",
  "testcontainers[rabbitmq]<4.16",
]
urls.Changelog = "https://lorrystream.readthedocs.io/changes.html"
urls.Documentation = "https://lorrystream.readthedocs.io/"
urls.Homepage = "https://lorrystream.readthedocs.io/"
urls.Issues = "https://github.com/daq-tools/lorrystream/issues"
urls.Repository = "https://github.com/daq-tools/lorrystream"
scripts.lorry = "lorrystream.cli:cli"
entry-points."streamz.sinks".dataframe_to_sql = "lorrystream.streamz.sinks:dataframe_to_sql"
entry-points."streamz.sources".from_amqp = "lorrystream.streamz.sources:from_amqp"
entry-points."streamz.sources".from_mqtt_plus = "lorrystream.streamz.sources:from_mqtt_plus"

[tool.setuptools]
packages.find.namespaces = false

# ===================
# Tasks configuration
# ===================
[tool.black]
line-length = 120
force-exclude = '''
  lorrystream/streamz/amqp.py
| lorrystream/carabas/aws/cf/.*\.py
'''

[tool.ruff]
line-length = 120
extend-exclude = [
  "amqp-to-mqtt.py",
  "dms_next\\.py$",
  "lorrystream/carabas/aws/cf/*.py",
  "lorrystream/streamz/amqp_async.py",
  "lorrystream/streamz/amqp_blocking.py",
  "workbench.py",
]
lint.select = [
  # Builtins
  "A",
  # Bugbear
  "B",
  # comprehensions
  "C4",
  # Pycodestyle
  "E",
  # eradicate
  "ERA",
  # Pyflakes
  "F",
  # isort
  "I",
  # pandas-vet
  "PD",
  # return
  "RET",
  # Bandit
  "S",
  # print
  "T20",
  "W",
  # flake8-2020
  "YTT",
]
lint.extend-ignore = [
  # zip() without an explicit strict= parameter
  "B905",
  # Unnecessary variable assignment before `return` statement
  "RET504",
  # Unnecessary `elif` after `return` statement
  "RET505",
]
lint.per-file-ignores."amazon_kclpy_helper.py" = [ "T201" ]  # Allow `print`
lint.per-file-ignores."examples/*" = [ "T201" ]  # Allow `print`
lint.per-file-ignores."lorrystream/util/about.py" = [ "T201" ]  # Allow `print`
lint.per-file-ignores."test_*.py" = [ "S101" ]  # Use of `assert` detected
lint.per-file-ignores."tests/*" = [ "S101" ]  # Use of `assert` detected

[tool.mypy]
packages = [ "lorrystream" ]
exclude = [
  "dms_next.py",
  "lorrystream/streamz/amqp_async.py",
  "lorrystream/streamz/amqp_blocking.py",
]
ignore_missing_imports = true
check_untyped_defs = true
implicit_optional = true
overrides = [ { module = "lorrystream.carabas.aws.cf.*", follow_imports = "silent" } ]
install_types = true
non_interactive = true

[tool.pytest]
ini_options.minversion = "2.0"
ini_options.testpaths = [
  "lorrystream",
  "tests",
]
# Because synchronous and asynchronous tests are mixed,
# and maybe because of woes with pytest fixtures, the
# test suite must turn off concurrency.
ini_options.addopts = """
  -rA --verbosity=3
  --cov --cov-report=term-missing --cov-report=xml
"""
ini_options.markers = [
  "slow",
]
ini_options.xfail_strict = true
ini_options.log_format = "%(asctime)-15s [%(name)-24s] %(levelname)-8s: %(message)s"
ini_options.log_level = "DEBUG"
ini_options.log_cli_level = "DEBUG"

[tool.coverage]
run.branch = false
run.omit = [
  "lorrystream/carabas/aws/function/zip.py",
  # It is tested, but code coverage tracking does not work well.
  "lorrystream/process/kinesis_cratedb_lambda.py",
  "lorrystream/spike/*",
  "tests/*",
]
run.source = [ "lorrystream" ]
report.fail_under = 0
report.show_missing = true

[tool.poe]
# ===================
# Tasks configuration
# ===================
tasks.check = [
  "lint",
  "test",
]
tasks.docs-autobuild = [
  { cmd = "sphinx-autobuild --open-browser --watch lorrystream doc doc/_build" },
]
tasks.docs-html = [
  { cmd = "sphinx-build -W --keep-going doc doc/_build" },
]
tasks.docs-linkcheck = [
  { cmd = "sphinx-build -W --keep-going -b linkcheck doc doc/_build" },
]
tasks.format = [
  { cmd = "black ." },
  # Configure Ruff not to auto-fix (remove!):
  # unused imports (F401), unused variables (F841), `print` statements (T201), and commented-out code (ERA001).
  { cmd = "ruff check --fix --ignore=ERA --ignore=F401 --ignore=F841 --ignore=T20 --ignore=ERA001 ." },
  { cmd = "pyproject-fmt --keep-full-version pyproject.toml" },
]
tasks.lint = [
  { cmd = "ruff check ." },
  { cmd = "black --check ." },
  { cmd = "validate-pyproject pyproject.toml" },
  { cmd = "mypy" },
]
tasks.release = [
  { cmd = "python -m build" },
  { cmd = "twine upload --skip-existing dist/*" },
]
tasks.test = { cmd = "pytest" }

[tool.versioningit]
vcs.method = "git"
vcs.default-tag = "0.0.0"
